### ISSUE TITLE
Stop using this for future document storage

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-policy/docs#3]
We should consolidate around a single repo for consistency.

I recommend using this folder instead in the future: https://github.com/monero-policy/monero-policy.github.io/tree/master/assets/pdfs

@umma08 thoughts?

**Comment by umma08** [comment]
@SamsungGalaxyPlayer I actually thought about this a while ago, as it confused me why they were separate. 

i think it was done by AJ so that PRs for the site and the docs would remain separated. I am sort of flexible to be honest, and don't have any preference either way. I know i stored some directly on the site in the past, but i am not certain that is any cleaner.

**Comment by ajs-xmr** [comment]
okay. I'll archive this repo then. Future docs should be uploaded to website's assets directory.
